services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck: # DB가 완전히 준비되었는지 확인
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: python_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db  # 도커 네트워크 안에서는 서비스명인 'db'로 접속합니다.